const opt = {
  code: {
    0: { code: 'Backquote' },
    1: { code: 'Digit1' },
    2: { code: 'Digit2' },
    3: { code: 'Digit3' },
    4: { code: 'Digit4' },
    5: { code: 'Digit5' },
    6: { code: 'Digit6' },
    7: { code: 'Digit7' },
    8: { code: 'Digit8' },
    9: { code: 'Digit9' },
    10: { code: 'Digit0' },
    11: { code: 'Minus' },
    12: { code: 'Equal' },
    13: { code: 'Backspace', ins: 'Backspace' },
    14: { code: 'Tab', ins: 'Tab' },
    15: { code: 'KeyQ' },
    16: { code: 'KeyW' },
    17: { code: 'KeyE' },
    18: { code: 'KeyR' },
    19: { code: 'KeyT' },
    20: { code: 'KeyY' },
    21: { code: 'KeyU' },
    22: { code: 'KeyI' },
    23: { code: 'KeyO' },
    24: { code: 'KeyP' },
    25: { code: 'BracketLeft' },
    26: { code: 'BracketRight' },
    27: { code: 'Backslash' },
    28: { code: 'Delete', ins: 'Del' },
    29: { code: 'CapsLock', ins: 'CapsLock' },
    30: { code: 'KeyA' },
    31: { code: 'KeyS' },
    32: { code: 'KeyD' },
    33: { code: 'KeyF' },
    34: { code: 'KeyG' },
    35: { code: 'KeyH' },
    36: { code: 'KeyJ' },
    37: { code: 'KeyK' },
    38: { code: 'KeyL' },
    39: { code: 'Semicolon' },
    40: { code: 'Quote' },
    41: { code: 'Enter', ins: 'Enter' },
    42: { code: 'ShiftLeft', ins: 'Shift' },
    43: { code: 'KeyZ' },
    44: { code: 'KeyX' },
    45: { code: 'KeyC' },
    46: { code: 'KeyV' },
    47: { code: 'KeyB' },
    48: { code: 'KeyN' },
    49: { code: 'KeyM' },
    50: { code: 'Comma' },
    51: { code: 'Period' },
    52: { code: 'Slash' },
    53: { code: 'ArrowUp', ins: '▲' },
    54: { code: 'ShiftRight', ins: 'Shift' },
    55: { code: 'ControlLeft', ins: 'Ctrl' },
    56: { code: 'AltLeft', ins: 'Alt' },
    57: { code: 'Space', ins: ' ' },
    58: { code: 'ControlRight', ins: 'Ctrl' },
    59: { code: 'ArrowLeft', ins: '◄' },
    60: { code: 'ArrowDown', ins: '▼' },
    61: { code: 'ArrowRight', ins: '►' },
  },
  ru: {
    Backquote: 'ё',
    Digit1: '1',
    Digit2: '2',
    Digit3: '3',
    Digit4: '4',
    Digit5: '5',
    Digit6: '6',
    Digit7: '7',
    Digit8: '8',
    Digit9: '9',
    Digit0: '0',
    Minus: '-',
    Equal: '=',
    KeyQ: 'й',
    KeyW: 'ц',
    KeyE: 'у',
    KeyR: 'к',
    KeyT: 'е',
    KeyY: 'н',
    KeyU: 'г',
    KeyI: 'ш',
    KeyO: 'щ',
    KeyP: 'з',
    BracketLeft: 'х',
    BracketRight: 'ъ',
    Backslash: '\\',
    KeyA: 'ф',
    KeyS: 'ы',
    KeyD: 'в',
    KeyF: 'а',
    KeyG: 'п',
    KeyH: 'р',
    KeyJ: 'о',
    KeyK: 'л',
    KeyL: 'д',
    Semicolon: 'ж',
    Quote: 'э',
    KeyZ: 'я',
    KeyX: 'ч',
    KeyC: 'с',
    KeyV: 'м',
    KeyB: 'и',
    KeyN: 'т',
    KeyM: 'ь',
    Comma: 'б',
    Period: 'ю',
    Slash: '.',
  },
  ruShift: {
    Backquote: 'Ё',
    Digit1: '!',
    Digit2: '"',
    Digit3: '№',
    Digit4: '$',
    Digit5: '%',
    Digit6: ':',
    Digit7: '?',
    Digit8: '*',
    Digit9: '(',
    Digit0: ')',
    Minus: '_',
    Equal: '+',
    KeyQ: 'Й',
    KeyW: 'Ц',
    KeyE: 'У',
    KeyR: 'К',
    KeyT: 'Е',
    KeyY: 'Н',
    KeyU: 'Г',
    KeyI: 'Ш',
    KeyO: 'Щ',
    KeyP: 'З',
    BracketLeft: 'Х',
    BracketRight: 'Ъ',
    Backslash: '/',
    KeyA: 'Ф',
    KeyS: 'Ы',
    KeyD: 'В',
    KeyF: 'А',
    KeyG: 'П',
    KeyH: 'Р',
    KeyJ: 'О',
    KeyK: 'Л',
    KeyL: 'Д',
    Semicolon: 'Ж',
    Quote: 'Э',
    KeyZ: 'Я',
    KeyX: 'Ч',
    KeyC: 'С',
    KeyV: 'М',
    KeyB: 'И',
    KeyN: 'Т',
    KeyM: 'Ь',
    Comma: 'Б',
    Period: 'Ю',
    Slash: ',',
  },
  en: {
    Backquote: '`',
    Digit1: '1',
    Digit2: '2',
    Digit3: '3',
    Digit4: '4',
    Digit5: '5',
    Digit6: '6',
    Digit7: '7',
    Digit8: '8',
    Digit9: '9',
    Digit0: '0',
    Minus: '-',
    Equal: '=',
    KeyQ: 'q',
    KeyW: 'w',
    KeyE: 'e',
    KeyR: 'r',
    KeyT: 't',
    KeyY: 'y',
    KeyU: 'u',
    KeyI: 'i',
    KeyO: 'o',
    KeyP: 'p',
    BracketLeft: '[',
    BracketRight: ']',
    Backslash: '\\',
    KeyA: 'a',
    KeyS: 's',
    KeyD: 'd',
    KeyF: 'f',
    KeyG: 'g',
    KeyH: 'h',
    KeyJ: 'j',
    KeyK: 'k',
    KeyL: 'l',
    Semicolon: ';',
    Quote: "'",
    KeyZ: 'z',
    KeyX: 'x',
    KeyC: 'c',
    KeyV: 'v',
    KeyB: 'b',
    KeyN: 'n',
    KeyM: 'm',
    Comma: ',',
    Period: '.',
    Slash: '/',
  },
  enShift: {
    Backquote: '~',
    Digit1: '!',
    Digit2: '@',
    Digit3: '#',
    Digit4: '$',
    Digit5: '%',
    Digit6: '^',
    Digit7: '&',
    Digit8: '*',
    Digit9: '(',
    Digit0: ')',
    Minus: '_',
    Equal: '+',
    KeyQ: 'Q',
    KeyW: 'W',
    KeyE: 'E',
    KeyR: 'R',
    KeyT: 'T',
    KeyY: 'Y',
    KeyU: 'U',
    KeyI: 'I',
    KeyO: 'O',
    KeyP: 'P',
    BracketLeft: '{',
    BracketRight: '}',
    Backslash: '|',
    KeyA: 'A',
    KeyS: 'S',
    KeyD: 'D',
    KeyF: 'F',
    KeyG: 'G',
    KeyH: 'H',
    KeyJ: 'J',
    KeyK: 'K',
    KeyL: 'L',
    Semicolon: ':',
    Quote: '"',
    KeyZ: 'Z',
    KeyX: 'X',
    KeyC: 'C',
    KeyV: 'V',
    KeyB: 'B',
    KeyN: 'N',
    KeyM: 'M',
    Comma: '<',
    Period: '>',
    Slash: '?',
  },
};

export default opt;
